---
- name: create directory 
  become: true
  file: 
    path: /home/ubuntu/web
    state: directory
    mode: 0755

- name: copy artifact
  become: true
  copy: 
    src: ~/project/backend-artifact.tar.gz
    dest: /home/ubuntu/web/backend-artifact.tar.gz

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -xvf backend-artifact.tar.gz

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/web/backend
    pm2 stop default
    pm2 delete all
    pm2 start npm -- start

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"